name: "Pull request"
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, closed]

jobs:
  pull_request:
    name: Actions
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/actions@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"